ClutterCollection {
 Clutter {
  ClutterDefinition "{66E52AB3D64B5D4A}" {
   ClutterConfig "{CCF8AAEDE657CF4D}Configs/Clutter/sirte_c_desert_trees_1.conf"
   Occurrence 1
  }
  ClutterDefinition "{66E52AB6DA3280EE}" {
   ClutterConfig "{8C588A6A94920F3A}Configs/Clutter/sirte_c_desert_stones_1.conf"
   Occurrence 3
  }
  ClutterDefinition "{66E52AB1117D4FE1}" {
   ClutterConfig "{4C33DF25162D8583}Configs/Clutter/sirte_c_desert_stones_2.conf"
   Occurrence 2
  }
  ClutterDefinition "{66E52ABF3FF8D5FD}" {
   ClutterConfig "{37B3F42950EEF0B2}Configs/Clutter/sirte_c_desert_grass_1.conf"
   Occurrence 6
  }
  ClutterDefinition "{66E52ABA97A53C16}" {
   ClutterConfig "{B2BDC85D16CBE1C7}Configs/Clutter/sirte_c_desert_grass_2.conf"
   Occurrence 2
  }
 }
}