SCR_MissionHeader {
 World "{53539624B766BAF5}GameMaster/GM_Sirte.ent"
 m_sName "Libya, Sirte by Triad Tactics Server. Game Master"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "Early September 2011 — the Libyan Civil War is approaching its climax. Gaddafi and the forces loyal to him are retreating to the city of Sirte, located on the Mediterranean coast."
 m_sIcon "{83A3BF515EE215A9}thumbnail.edds"
 m_sLoadingScreen "{8811728E8293B9AD}1.edds"
 m_sPreviewImage "{83A3BF515EE215A9}thumbnail.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}