ClutterConfig {
 Model "{3D5D392E146DA3E5}Assets/Clutter/Vegetation/Plant/Carduus_acanthoides/c_Carduus_acanthoides_dry_01.xob"
 MinScale 0.2
 MaxScale 0.5
 UseTerrainNormal 1
 SnapToTerrain 1
 ZenithOffset 0
 Overlap 0
 Density 0.04
 Thinning 0
 LodBias 3
}