ClutterConfig {
 Model "{FF3FB8C2EC5C4F26}Assets/Clutter/Vegetation/Plant/Calluna_vulgaris/c_calluna_vulgaris_dry_02.xob"
 MinScale 1
 MaxScale 2
 UseTerrainNormal 1
 SnapToTerrain 1
 ZenithOffset 0
 Overlap 0
 Density 0.005
 Thinning 0.9
 LodBias 3
}